packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@swc/core'

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  next@<14.2.24: '>=14.2.24'
  next@=13.5.9: '>=13.5.10'
  next@>=10.0.0 <14.2.7: '>=14.2.7'
  next@>=13.0 <14.2.30: '>=14.2.30'
  next@>=13.4.0 <14.1.1: '>=14.1.1'
  next@>=9.5.5 <14.2.15: '>=14.2.15'
